version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: agentforce-postgres
    environment:
      POSTGRES_USER: agentforce
      POSTGRES_PASSWORD: agentforce
      POSTGRES_DB: agentforce
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: agentforce-redis
    command: ["redis-server", "--appendonly", "no"]
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.106.1
    container_name: agentforce-otel
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./configs/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"

  grafana:
    image: grafana/grafana:11.1.0
    container_name: agentforce-grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "5400:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data:
  redis_data:
  grafana_data:


